rango/urls.py
from django.urls import path
from rango import views

app_name='rango'

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('category/<slug:category_name_slug>/',views.show_category,name='show_category'),
    path('add_category/',views.add_category,name='add_category'),
    path('category/<slug:category_name_slug>/add_page/',views.add_page,name='add_page'),
    # path('register/',views.register,name='register'),
    # path('login/',views.user_login,name='login'),
    path('restricted/',views.restricted,name='restricted'),
    # path('logout/',views.user_logout,name='logout'),
    path('/rango/search/',views.search,name='search'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.simple.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data=self.cleaned_data
        url=cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url=f'http://{url}'
            cleaned_data['url']=url
        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture',)

rango/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse

from rango.models import Category
from rango.models import Page

from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)

    response = render(request, 'rango/index.html', context=context_dict)

    return response


def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    print(request.method)
    print(request.user)

    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if user_login is False:
        return redirect(reverse('rango:login'))

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():

            form.save(commit=True)

            return redirect(reverse('rango:index'))
        else:

            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse('Your Rango account is disabled.')
        else:
            print(f"Invalid login details:{username},{password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
        # response.set_cookie('last_visit',str(datetime.now()))
    else:
        request.session['last_visit'] = last_visit_cookie
        # response.set_cookie('last_visit', last_visit_cookie)
    request.session['visits'] = visits
    # response.set_cookie('visits',visits)

def search(request):
    result_list=[]
    query = ''

    if request.method=='POST':
        query = request.POST['query'].strip()
        if query:
            result_list=run_query(query)
    return render(request,'rango/search.html',{'result_list':result_list,'query':query})

templates/rango/about.html
<!DOCTYPE html>
<html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
<head>
    <title>
{% block title_block %}
    About Rango
{% endblock %}
    </title>
</head>

<body>




{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page. <br />
        <strong>{{ boldmessage }}</strong><br />
        <p>Visits: {{ visits }}</p>
    </div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /><br />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." /><br />
{% endblock %}
</body>



</html>

templates/rango/add_category.html
<!DOCTYPE html>
<html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
<head>
    <title>
        {% block title_block %}
        Add a Category
        {% endblock %}
    </title>
</head>

<body>

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Category</h1>
    </div>
</div>
<div class="container">


    <div class="row">
        <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}<br />
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
            <div class="p-5"></div>

        </form>

    </div>

</div>
{% endblock %}

</body>

</html>

templates/rango/add_page.html
<!DOCTYPE html>
<html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
<head>
    <title>{% block title_block %}
    Add a Page
{% endblock %}
    </title>
</head>

<body>

{% block body_block %}

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
    </div>
</div>

<div class="container">
    <div class="row">
         <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
             <br />
             <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
             <div class="p-5"></div>
        </form>
    </div>
</div>


{% endblock %}

</body>

</html>

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>

<head lang="en">
    <meta charset="UTF-8" />
    <title>
        Rango -
        {% block title_block %}
        How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
        {% get_category_list category %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index'%}">Logout</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            <li><a href="{% url 'auth_password_change'%}?next={% url 'auth_password_change_done'%}">Change Password</a></li>
            {% else %}
            <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
            <li><a href="{% url 'auth_login' %}?next={% url 'rango:index'%}">Login</a></li>
            {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>

</body>

</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:search' %}">Search</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul class="nav flex-column">
    {% if categories %}
       {% for c in categories %}
          {% if c == current_category %}
            <li class="nav-item">
                 <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}" ><span data-feather="archive">
                     </span>{{ c.name }}</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive">
                     </span>{{ c.name }}</a>
            </li>
          {% endif %}
       {% endfor %}
    {% else %}
       <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

</body>
</html>

templates/rango/category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
<html>
<head>
    <title>
        {% block title_block %}
            {% if category %}
              {{ category.name }}
            {% else %}
               Unknown Category
            {% endif %}
        {% endblock %}
    </title>
</head>

<body>
    <div>

        {% block body_block %}
        {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{page.url}}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br/>
        {% endif %}
        {% else %}
          The specified category does not exist.
        {% endif %}
        {% endblock %}
    </div>
    <div>
        <a href="/rango/">Back</a>
    </div>
</body>



</html>

templates/rango/index.html
<!DOCTYPE html>
<html>
{% extends 'rango/base.html' %}
{% load staticfiles %}

<head>
    <title>
        {% block title_block %}
        Homepage
        {% endblock %}
    </title>
</head>

<body>

{% block body_block %}

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
            <h2 class="h2">
                {% if user.is_authenticated %}
                howdy {{ user.username }}!
                {% else %}
                hey there partner!
                {% endif %}
            </h2>
            <strong>{{ boldmessage }}</strong><br/>
        </div>

    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Liked Categories</h2>
                    {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no categories present.</strong>
                    {% endif %}
                </div>

            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Viewed Pages</h2>
                    {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{{ page.url }}">{{ page.title }}</a>
                        </li>
                        {% endfor%}
                    </ul>
                    {% else %}
                    <strong>There are no pages present.</strong>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


</div>

<div>

</div>
<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango">
{% endblock %}
</body>


</html>

templates/rango/login.html
<!DOCTYPE html>
<html lang="en">
{% extends 'rango/base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        Login
        {% endblock %}
    </title>
</head>

<body>
    {% block body_block %}
    <h1>Login to Rango</h1>
    
    <form id="login_form" method="POST" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" /><br />
        Password: <input type="password" name="password" value="" size="50" /><br />


        <input type="submit" value="submit" />
    </form>
    
    {% endblock %}

</body>

</html>

templates/rango/register.html
<!DOCTYPE html>
<html lang="en">
{% extends 'rango/base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        Register
        {% endblock %}
    </title>
</head>

<body>
    {% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
    Rango says: <strong>thank you for registering!</strong>
    <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
    Rango says: <strong>register here!</strong><br />
    <form id="user_form" method="POST" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="submit" value="Register" />
    </form>
    {% endif %}
    {% endblock %}

</body>

</html>

templates/rango/restricted.html
<!DOCTYPE html>
<html lang="en">
{% extends 'rango/base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        Restricted Page
        {% endblock %}
    </title>
</head>

<body>
    {% block body_block %}
    <h1>Restricted Page</h1>
    Since you're logged in, you can see this text!<br />
    HELLO!
    {% endblock %}

</body>

</html>

templates/rango/search.html
<!DOCTYPE html>
<html lang="en">
{% extends 'rango/base.html' %}
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title_block %}
        Search
        {% endblock %}</title>
</head>
<body>


{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Search with Rango</h1>
    </div>
</div>
<div>
    <form class="form-inline" id="user-form" method="post" action="{% url 'rango:search' %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" id="query" value="{{ query }}"/>
        </div>

        <button class="btn btn-primary" type="submit" name="submit">Search</button>
    </form>
</div>
<div>
    {% if result_list %}
    <h2>Results</h2>

    <div class="list-group">
        {% for result in result_list %}
        <div class="list-group-item">
            <h3 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
            </h3>
            <p class="list-group-item-text">
                {{ result.summary|safe|escape }}
            </p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

</body>
</html>